### ISSUE TITLE
Fails to parse

### ISSUE THREAD

**Issue by Avenred** [BlueTree242/PAPIMiniColors#1]
After running `/papi parse me %minim_vault_prefix%`, it fails and prints the following error into console:
```
[10:46:17 ERROR]: Command exception: /papi parse me %minim_vault_prefix%
org.bukkit.command.CommandException: Unhandled exception executing command 'papi' in plugin PlaceholderAPI v2.11.6
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:456) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.commands.Commands.performCommand(Commands.java:363) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.commands.Commands.performCommand(Commands.java:350) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.commands.Commands.performCommand(Commands.java:345) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2282) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$18(ServerGamePacketListenerImpl.java:2256) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1546) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1523) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1446) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1412) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1273) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: dev/bluetree242/minim/dependencies/adventure/text/serializer/legacy/LegacyComponentSerializer
	at dev.bluetree242.minim.MiniMExpansion.convert(MiniMExpansion.java:48) ~[?:?]
	at dev.bluetree242.minim.MiniMExpansion.onRequest(MiniMExpansion.java:38) ~[?:?]
	at PlaceholderAPI-2.11.6.jar/me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[PlaceholderAPI-2.11.6.jar:?]
	at PlaceholderAPI-2.11.6.jar/me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) ~[PlaceholderAPI-2.11.6.jar:?]
	at PlaceholderAPI-2.11.6.jar/me.clip.placeholderapi.commands.impl.local.CommandParse.evaluateParseSingular(CommandParse.java:118) ~[PlaceholderAPI-2.11.6.jar:?]
	at PlaceholderAPI-2.11.6.jar/me.clip.placeholderapi.commands.impl.local.CommandParse.evaluate(CommandParse.java:57) ~[PlaceholderAPI-2.11.6.jar:?]
	at PlaceholderAPI-2.11.6.jar/me.clip.placeholderapi.commands.PlaceholderCommandRouter.onCommand(PlaceholderCommandRouter.java:114) ~[PlaceholderAPI-2.11.6.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	... 26 more
Caused by: java.lang.ClassNotFoundException: dev.bluetree242.minim.dependencies.adventure.text.serializer.legacy.LegacyComponentSerializer
	at dev.bluetree242.minim.MiniMExpansion.convert(MiniMExpansion.java:48) ~[?:?]
	at dev.bluetree242.minim.MiniMExpansion.onRequest(MiniMExpansion.java:38) ~[?:?]
	at PlaceholderAPI-2.11.6.jar/me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119) ~[PlaceholderAPI-2.11.6.jar:?]
	at PlaceholderAPI-2.11.6.jar/me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71) ~[PlaceholderAPI-2.11.6.jar:?]
	at PlaceholderAPI-2.11.6.jar/me.clip.placeholderapi.commands.impl.local.CommandParse.evaluateParseSingular(CommandParse.java:118) ~[PlaceholderAPI-2.11.6.jar:?]
	at PlaceholderAPI-2.11.6.jar/me.clip.placeholderapi.commands.impl.local.CommandParse.evaluate(CommandParse.java:57) ~[PlaceholderAPI-2.11.6.jar:?]
	at PlaceholderAPI-2.11.6.jar/me.clip.placeholderapi.commands.PlaceholderCommandRouter.onCommand(PlaceholderCommandRouter.java:114) ~[PlaceholderAPI-2.11.6.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	... 26 more
```

I am running `Purpur Version: 1.20.6-2233-0d6766e (MC: 1.20.6)*` as the server jar.

**Comment by BlueTree242** [comment]
The jar you're using is not shaded for some reason

**Comment by Avenred** [comment]
Do you have a jar that is? I downloaded the jar from https://api.extendedclip.com/expansions/minimexpansion/

**Comment by BlueTree242** [comment]
Nevermind the legacy serializer is missing from the jar. Thank you for reporting this, I will fix this as fast as possible

**Comment by BlueTree242** [comment]
The expansion has been updated.
